services:
#    iam_ip.example:
#        class: Iam\IPBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

maxmind.geoip:
    class:      Maxmind\Bundle\GeoipBundle\Service\GeoipManager
    arguments:  [@kernel]